version: '2'
services:
  elasticapp-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/ElasticApp/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ElasticApp
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
